---
name: CI

on: [ push, pull_request ]

jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ 7.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-versions }}"
      - name: "Install composer"
        uses: "ramsey/composer-install@v1"
      - name: "Run PHP lint"
        run: composer run-script test-php-lint
  php-cs-fixer:
    name: "PHP-CS-Fixer"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ 7.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-versions }}"
      - name: "Install composer"
        uses: "ramsey/composer-install@v1"
      - name: "Run PHP-CS-Fixer"
        run: "composer run-script test-php-cs-fixer"
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        php-versions: [ 7.4 ]
        typo3-versions:
          - { typo3: 10, testing: 6 }
          - { typo3: 11, testing: 6 }

    name: "Run tests with PHP ${{ matrix.php-versions }}
          using TYPO3 ${{ matrix.typo3-versions.typo3 }}
          with testing framework version ${{ matrix.typo3-versions.testing }}"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, pdo_sqlite, pdo_mysql
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: "Install composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "lowest"
      - name: "Install optional dependencies"
        run: composer require typo3/minimal
          "^${{ matrix.typo3-versions.typo3 }}"
          typo3/testing-framework "^${{ matrix.typo3-versions.testing }}"
          --prefer-dist --no-progress --with-all-dependencies
      - name: "Run Unit tests"
        run: composer run-script test-unit
      - name: "Functional tests"
        run: |
          export typo3DatabaseName="typo3";
          export typo3DatabaseHost="127.0.0.1";
          export typo3DatabaseUsername="root";
          export typo3DatabasePassword="root";
          composer run-script test-functional
